### ISSUE TITLE
Bower registration switch

### ISSUE THREAD

**Issue by desandro** [blmarket/masonry-layout#1]
Hello!

I'm the author of [Masonry](https://masonry.desandro.com). I've run into a name mis-match issue on metafizzy/isotope#1129. React developers are unable to use create-react-app with Isotope & Masonry because of name mismatch issues for Masonry between npm `masonry-layout` and Bower `masonry`.

With your generosity I could resolve this issue. Would you please [un-register this package on Bower](https://bower.io/docs/api/#unregister), so that I may takeover `masonry-layout`? This way, Masonry's package manager registration would match.

Masonry remains wildly popular (12,000 GitHub stars). Resolving this mismatch would help lots of developers out there.

**Comment by blmarket** [comment]
Sure! Thanks for good product tho.

**Comment by desandro** [comment]
Thank you so much! [If you like stickers](https://i.imgur.com/5RfF9Qa.jpg), email me yo@metafizzy.co so I can send some your way!
